(function(){
'use strict';
var SB_URL='https://bnnhmtkpdjlgehsvgoda.supabase.co';
var SB_KEY='sb_publishable_eXrgSxWTXoa9q-hVpLx-sQ_IaEiUbeO';
var TOKEN_KEY='hasnaria-staff-session-v1';
var AUTH_KEY='hasnaria-auth-v2';
var MAP_URL='https://maps.app.goo.gl/WzUKVnPrLrLG9CbQ8';
var ADDRESS='Jl. Kates No.71, Utara, MAN1, Kec. Boyolali, Kabupaten Boyolali, Jawa Tengah 57311';
var db=null;
var state={view:'login',dir:[],staff:null,token:'',module:'home',sub:'',msg:'',today:null,hist:[],corr:[],month:new Date(),selected:'',geo:null,owner:null,ownerRows:[],approvals:[],loc:null,ownerTab:'users',edit:null,employeeDetailOpen:false};
function pad(n){return String(n).padStart(2,'0');}
function iso(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());}
state.selected=iso(new Date());
function el(id){return document.getElementById(id);}
function root(){return el('staffRoot');}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function errText(e){return e&&e.message?e.message:String(e||'Terjadi kesalahan.');}
function fmtDate(d){return new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);}
function fmtMonth(d){return new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(d);}
function snapshotDate(){try{return new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(new Date());}catch(_){return iso(new Date());}}
function fmtTime(v){if(!v)return '—';try{return new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'}).format(new Date(v)).replace('.',':');}catch(_){return String(v).slice(0,5);}}
function now(){return new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit'}).format(new Date()).replace('.',':');}
function coords(v){return typeof v==='number'&&isFinite(v)?v.toFixed(6):'—';}
function meters(v){return typeof v==='number'&&isFinite(v)?(v<1000?Math.round(v)+' m':(v/1000).toFixed(2)+' km'):'—';}
function storedToken(){try{return localStorage.getItem(TOKEN_KEY)||'';}catch(_){return '';}}
function saveToken(v){try{if(v)localStorage.setItem(TOKEN_KEY,v);else localStorage.removeItem(TOKEN_KEY);}catch(_){}}
function hasModule(k){return !!(state.staff&&Array.isArray(state.staff.modules)&&state.staff.modules.indexOf(k)>=0);}
function client(){if(db)return db;if(!window.supabase||!window.supabase.createClient)throw new Error('Library login belum termuat. Muat ulang halaman.');db=window.supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:AUTH_KEY}});return db;}
async function rpc(name,args){var r=await client().rpc(name,args||{});if(r.error)throw r.error;return r.data||[];}
function top(label,action,title){return '<header class="staff-top"><div class="staff-brand"><img src="/hasnaria-logo.svg" alt="Hasnaria"><div class="staff-brand-copy"><b>'+esc(title||'Staff Portal')+'</b><span>Hasnaria · Mobile Workspace</span></div></div>'+(label?'<button class="staff-top-action" data-act="'+esc(action)+'">'+esc(label)+'</button>':'')+'</header>';}
function note(){return state.msg?'<div class="staff-msg">'+esc(state.msg)+'</div>':'';}
function nav(){var a=[['home','⌂','Home'],['absensi','✓','Absensi'],['kasir','▣','Kasir'],['gudang','□','Gudang']];return '<nav class="staff-nav">'+a.map(function(x){var ok=x[0]==='home'||hasModule(x[0]);return '<button data-mod="'+x[0]+'" class="'+(state.module===x[0]?'on':'')+'" '+(ok?'':'disabled')+'><span class="nav-icon">'+x[1]+'</span><span>'+x[2]+'</span></button>';}).join('')+'</nav>';}
function loginView(){var opts=state.dir.map(function(x){return '<option value="'+esc(x.employee_id)+'">'+esc(x.full_name)+'</option>';}).join('');return '<div class="staff-shell">'+top('Owner','owner-open')+'<section class="staff-content"><div class="staff-card staff-hero"><div class="staff-eyebrow">Portal Pegawai</div><h1>Masuk kerja lebih cepat.</h1><p>Pilih nama dan masukkan PIN 6 digit.</p>'+(state.dir.length?'<label class="staff-field"><span>Nama pegawai</span><select id="emp"><option value="">Pilih nama pegawai</option>'+opts+'</select></label><label class="staff-field"><span>PIN</span><input id="pin" class="staff-pin" type="password" inputmode="numeric" maxlength="6" placeholder="••••••"></label><button class="staff-btn primary" data-act="staff-login">Masuk</button>':'<div class="staff-empty"><h2>Belum ada akun staff aktif</h2><p>Owner perlu mengaktifkan akun dan menetapkan PIN.</p><button class="staff-btn primary" data-act="owner-open">Setup oleh Owner</button></div>')+note()+'<div class="staff-login-owner"><button class="staff-link-btn" data-act="owner-open">Kelola sebagai Owner</button></div></div></section></div>';}
function homeView(){var mods={absensi:['✓','Absensi','Clock in, riwayat, dan koreksi kehadiran'],kasir:['▣','Kasir','Transaksi keuangan Penjualan dan Pembelian'],gudang:['□','Gudang','Stok, penerimaan, dan opname']};return '<div class="staff-shell">'+top('Keluar','staff-out')+'<section class="staff-content"><div class="staff-card staff-greeting"><div class="staff-eyebrow">Selamat bekerja</div><h1>Halo, '+esc(state.staff.fullName)+'</h1><p>Pilih fungsi yang dibutuhkan.</p><div class="staff-tiles">'+Object.keys(mods).map(function(k){var m=mods[k],ok=hasModule(k);return '<button class="staff-tile '+(ok?'':'locked')+'" data-mod="'+k+'" '+(ok?'':'disabled')+'><span class="tile-icon">'+m[0]+'</span><span><strong>'+m[1]+'</strong><small>'+(ok?m[2]:'Belum ditugaskan Owner')+'</small></span><span class="arrow">›</span></button>';}).join('')+'</div></div></section>'+nav()+'</div>';}
function attendanceMenu(){var a=[['clock','☉','Clock In - Clock Out','Absen masuk dan pulang dalam radius 50 m'],['history','▤','Riwayat','Riwayat kehadiran anda'],['summary','▤','Kehadiran Saya','Ringkasan kehadiran bulan ini'],['corr','✎','Koreksi Kehadiran','Ajukan koreksi manual ke Owner'],['mine','◷','Koreksi Saya','Status persetujuan koreksi'],['schedule','◔','Waktu Kerja','Jadwal kerja yang tersedia']];return '<div class="staff-shell attendance-shell">'+top(state.staff.fullName,'staff-out')+'<section class="staff-content"><div class="attendance-page-title"><div><h1>Kehadiran</h1><p>Absensi normal tidak perlu approval bila berada ≤ 50 m dari Warung Hasnaria.</p></div></div><div class="attendance-menu-list">'+a.map(function(x){return '<button class="attendance-menu-card" data-sub="'+x[0]+'"><span class="attendance-menu-icon">'+x[1]+'</span><span><strong>'+x[2]+'</strong><small>'+x[3]+'</small></span><span>›</span></button>';}).join('')+'</div>'+note()+'</section>'+nav()+'</div>';}
function dist(lat,lng,a,b){var R=6371000,r=function(x){return x*Math.PI/180;},d1=r(a-lat),d2=r(b-lng),z=Math.sin(d1/2)*Math.sin(d1/2)+Math.cos(r(lat))*Math.cos(r(a))*Math.sin(d2/2)*Math.sin(d2/2);return 2*R*Math.atan2(Math.sqrt(z),Math.sqrt(1-z));}
function gps(){if(!navigator.geolocation){state.geo={error:'GPS tidak tersedia'};render();return;}state.geo={loading:true};render();navigator.geolocation.getCurrentPosition(function(p){var t=state.today,d=null;if(t&&t.location_configured)d=dist(p.coords.latitude,p.coords.longitude,t.office_lat,t.office_lng);state.geo={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,distance:d,inRange:d!=null&&d<=50};render();},function(e){state.geo={error:e.message||'Izin lokasi ditolak'};render();},{enableHighAccuracy:true,timeout:12000,maximumAge:30000});}
function clockView(){var t=state.today||{},g=state.geo||{},inside=!!g.inRange,configured=!!t.location_configured,ci=t.check_in_at,co=t.check_out_at,status=!configured?'Titik Warung belum diset Owner':g.error?g.error:g.loading?'Memeriksa lokasi...':inside?'Anda berada dalam radius Warung Hasnaria':'Anda berada di luar radius 50 m';return '<div class="staff-shell attendance-shell">'+top('Kembali','att-back')+'<section class="attendance-full-head"><div class="attendance-title-row"><div><h1>Kehadiran</h1><p>'+esc(fmtDate(new Date()))+'</p><div class="attendance-time-big">'+esc(now())+'</div></div><div class="attendance-office-pill">'+esc(t.outlet_name||'Hasnaria')+'</div></div></section><section class="staff-content staff-content-tight"><div class="attendance-illustration-card"><div class="attendance-alert '+(inside?'ok':'warn')+'">'+esc(status)+'</div><div class="attendance-geo-meta"><div><b>Jarak</b><span>'+meters(g.distance)+'</span></div><div><b>GPS saat ini</b><span>'+coords(g.lat)+' / '+coords(g.lng)+'</span></div><div><b>Titik Warung</b><span>'+coords(t.office_lat)+' / '+coords(t.office_lng)+'</span></div></div><div class="attendance-times"><div><span>Masuk</span><strong>'+fmtTime(ci)+'</strong></div><div><span>Pulang</span><strong>'+fmtTime(co)+'</strong></div></div><div class="attendance-action-row"><button class="staff-btn success" data-clock="in" '+(inside&&!ci?'':'disabled')+'>Clock In</button><button class="staff-btn danger-solid" data-clock="out" '+(inside&&ci&&!co?'':'disabled')+'>Clock Out</button></div><button class="staff-btn ghost" data-act="gps">Perbarui Lokasi</button><div class="attendance-footnote">Absensi normal langsung tersimpan tanpa approval. Di luar radius, gunakan Koreksi Kehadiran manual.</div>'+note()+'</div></section>'+nav()+'</div>';}
function historyView(){var y=state.month.getFullYear(),m=state.month.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),map={};state.hist.forEach(function(x){map[x.attendance_date]=x;});var cells='';for(var i=0;i<first.getDay();i++)cells+='<div></div>';for(var d=1;d<=last.getDate();d++){var k=iso(new Date(y,m,d)),x=map[k],mark=x?(x.check_in_at?'✓':'•'):'';cells+='<button class="attendance-cal-cell '+(state.selected===k?'selected':'')+'" data-day="'+k+'"><span>'+d+'</span><span class="mark '+(x&&x.check_in_at?'check':'dot')+'">'+mark+'</span></button>';}var s=map[state.selected]||{};return '<div class="staff-shell attendance-shell">'+top('Kembali','att-back')+'<section class="staff-content"><div class="attendance-page-title"><h1>Riwayat Kehadiran</h1></div><div class="attendance-month-nav"><button class="icon-btn" data-month="-1">‹</button><b>'+esc(fmtMonth(state.month))+'</b><button class="icon-btn" data-month="1">›</button></div><div class="attendance-calendar"><div class="attendance-weekdays">'+['MIN','SEN','SEL','RAB','KAM','JUM','SAB'].map(function(x){return '<span>'+x+'</span>';}).join('')+'</div><div class="attendance-cal-grid">'+cells+'</div></div><div class="attendance-detail-card"><h2>'+esc(fmtDate(new Date(state.selected+'T00:00:00')))+'</h2><p>Masuk: <b>'+fmtTime(s.check_in_at)+'</b> · Pulang: <b>'+fmtTime(s.check_out_at)+'</b></p><button class="staff-btn primary" data-sub="corr">Koreksi Kehadiran</button></div></section>'+nav()+'</div>';}
function correctionView(){return '<div class="staff-shell attendance-shell">'+top('Kembali','att-back')+'<section class="staff-content"><div class="attendance-page-title"><div><h1>Koreksi Kehadiran</h1><p>Hanya koreksi manual yang memerlukan persetujuan Owner.</p></div></div><label class="staff-field"><span>Tipe *</span><select id="ctype"><option value="check_in">Clock In</option><option value="check_out">Clock Out</option></select></label><div class="attendance-form-grid"><label class="staff-field"><span>Tanggal *</span><input id="cdate" type="date" value="'+esc(state.selected)+'"></label><label class="staff-field"><span>Waktu *</span><input id="ctime" type="time"></label></div><label class="staff-field"><span>Alasan *</span><textarea id="creason" rows="5" placeholder="Jelaskan alasan koreksi"></textarea></label><button class="staff-btn primary" data-act="submit-corr">Kirim untuk Persetujuan Owner</button>'+note()+'</section>'+nav()+'</div>';}
function mineView(){return '<div class="staff-shell attendance-shell">'+top('Kembali','att-back')+'<section class="staff-content"><div class="attendance-page-title"><div><h1>Koreksi Saya</h1><p>Status koreksi manual yang pernah diajukan.</p></div></div><div class="attendance-backlog-list">'+(state.corr.length?state.corr.map(function(x){return '<div class="attendance-backlog-item"><div><b>'+(x.correction_type==='check_out'?'Clock Out':'Clock In')+' · '+esc(x.attendance_date)+'</b><small>'+esc(String(x.requested_time||'').slice(0,5))+'</small><p>'+esc(x.reason||'')+'</p></div><span class="status-pill '+(x.status==='approved'?'on':'')+'">'+esc(x.status)+'</span></div>';}).join(''):'<div class="staff-card">Belum ada koreksi.</div>')+'</div></section>'+nav()+'</div>';}
function summaryView(){var p=state.hist.filter(function(x){return !!x.check_in_at;}).length,late=state.hist.filter(function(x){return x.attendance_status==='late';}).length,pending=state.corr.filter(function(x){return x.status==='pending';}).length;return '<div class="staff-shell attendance-shell">'+top('Kembali','att-back')+'<section class="staff-content"><div class="attendance-page-title"><div><h1>Kehadiran Saya</h1><p>'+esc(fmtMonth(state.month))+'</p></div></div><div class="attendance-summary-grid"><div class="attendance-summary-card"><strong>'+p+'</strong><span>Hari hadir</span></div><div class="attendance-summary-card"><strong>'+late+'</strong><span>Terlambat</span></div><div class="attendance-summary-card"><strong>'+pending+'</strong><span>Koreksi pending</span></div><div class="attendance-summary-card"><strong>50 m</strong><span>Radius absensi</span></div></div></section>'+nav()+'</div>';}
function scheduleView(){var t=state.today||{};return '<div class="staff-shell attendance-shell">'+top('Kembali','att-back')+'<section class="staff-content"><div class="attendance-page-title"><div><h1>Waktu Kerja</h1><p>Jadwal yang tersedia untuk hari ini.</p></div></div><div class="attendance-panel-list"><div class="attendance-panel-row"><b>Shift</b><span>'+esc(t.shift_name||'Belum dijadwalkan')+'</span></div><div class="attendance-panel-row"><b>Jam</b><span>'+esc(String(t.shift_start||'—').slice(0,5))+' - '+esc(String(t.shift_end||'—').slice(0,5))+'</span></div><div class="attendance-panel-row"><b>Lokasi</b><span>'+esc(t.outlet_name||'Hasnaria Main')+'</span></div></div></section>'+nav()+'</div>';}
function attendanceView(){if(state.sub==='clock')return clockView();if(state.sub==='history')return historyView();if(state.sub==='summary')return summaryView();if(state.sub==='corr')return correctionView();if(state.sub==='mine')return mineView();if(state.sub==='schedule')return scheduleView();return attendanceMenu();}
function kasirView(){if(!state.sub)return '<div class="staff-shell">'+top('Kembali','mod-back')+'<section class="staff-content"><div class="staff-card"><div class="staff-module-head"><div class="big-icon">▣</div><div><h1>Kasir</h1><p>Transaksi keuangan Penjualan dan Pembelian</p></div></div><div class="staff-tiles"><button class="staff-tile" data-sub="penjualan"><span class="tile-icon">↑</span><span><strong>Penjualan</strong><small>Transaksi penjualan dan penerimaan pembayaran</small></span></button><button class="staff-tile" data-sub="pembelian"><span class="tile-icon">↓</span><span><strong>Pembelian</strong><small>Transaksi pembelian dan pengeluaran usaha</small></span></button></div></div></section>'+nav()+'</div>';return '<div class="staff-shell">'+top('Kembali','kasir-back')+'<section class="staff-content"><div class="staff-card"><h1>'+(state.sub==='penjualan'?'Penjualan':'Pembelian')+'</h1><p class="staff-note">Menu transaksi siap disambungkan ke alur keuangan Hasnaria.</p></div></section>'+nav()+'</div>';}
function ownerLoginView(){return '<div class="staff-shell">'+top('Kembali','login-back','Owner Mobile')+'<section class="staff-content"><div class="staff-card staff-hero"><div class="staff-eyebrow">Owner Mobile</div><h1>Masuk sebagai Owner</h1><p>Gunakan akun Owner yang sama dengan web Hasnaria utama.</p><label class="staff-field"><span>Email</span><input id="oemail" type="email"></label><label class="staff-field"><span>Password</span><input id="opass" type="password"></label><button class="staff-btn primary" data-act="owner-login">Masuk</button>'+note()+'</div></section></div>';}
function ownerNav(){return '<div class="owner-mobile-nav"><button data-otab="users" class="'+(state.ownerTab==='users'?'on':'')+'"><b>Akun Staff</b><small>'+state.ownerRows.length+' pegawai</small></button><button data-otab="approvals" class="'+(state.ownerTab==='approvals'?'on':'')+'"><b>Persetujuan</b><small>'+state.approvals.length+' koreksi</small></button><button data-otab="location" class="'+(state.ownerTab==='location'?'on':'')+'"><b>Lokasi Absensi</b><small>'+(state.loc&&state.loc.configured?'Aktif · 50 m':'Belum diset')+'</small></button></div>';}
function userEditView(){if(!state.edit)return '';var x=state.edit;function ch(k){return (x.modules||[]).indexOf(k)>=0?'checked':'';}return '<div class="staff-card"><h2>'+(x.employee_id?'Atur Staff':'Tambah Pegawai')+'</h2><label class="staff-field"><span>Nama</span><input id="ename" value="'+esc(x.full_name||'')+'"></label><label class="staff-field"><span>'+(x.pin_set?'PIN baru (opsional)':'PIN 6 digit')+'</span><input id="epin" class="staff-pin" type="password" inputmode="numeric" maxlength="6"></label><div class="owner-checks"><label class="owner-check"><input id="ma" type="checkbox" '+ch('absensi')+'>Absensi</label><label class="owner-check"><input id="mk" type="checkbox" '+ch('kasir')+'>Kasir</label><label class="owner-check"><input id="mg" type="checkbox" '+ch('gudang')+'>Gudang</label></div><label class="owner-active"><span>Aktifkan login</span><input id="eactive" type="checkbox" '+(x.staff_active?'checked':'')+'></label><div class="staff-inline"><button class="staff-btn ghost" data-act="cancel-edit">Batal</button><button class="staff-btn primary" data-act="save-user">Simpan</button></div>'+note()+'</div>';}
function usersView(){
  var active=state.ownerRows.filter(function(x){return x.staff_active}).length;
  var pin=state.ownerRows.filter(function(x){return x.pin_set}).length;
  var assigned=state.ownerRows.filter(function(x){return Array.isArray(x.modules)&&x.modules.length}).length;
  var list=state.ownerRows.map(function(x){return '<div class="owner-person"><div><b>'+esc(x.full_name)+'</b><small>'+esc((x.modules||[]).join(', ')||'Belum ditugaskan')+'</small><span class="status-pill '+(x.staff_active?'on':'')+'">'+(x.staff_active?'Aktif':'Belum aktif')+(x.pin_set?' · PIN siap':' · PIN belum diset')+'</span></div><button data-edit="'+esc(x.employee_id)+'">Atur</button></div>';}).join('')||'<div class="staff-empty"><h2>Belum ada pegawai</h2></div>';
  var modal=state.employeeDetailOpen?'<div class="ui7-staff-modal-backdrop"><section class="ui7-staff-modal" role="dialog" aria-modal="true" aria-labelledby="ui7StaffTitle"><div class="ui7-staff-modal-head"><div><div class="staff-eyebrow">DETAIL PEGAWAI</div><h2 id="ui7StaffTitle">Kelola Staff PIN</h2><p>PIN, modul kerja, status login, dan penugasan tetap menggunakan alur Staff yang sama.</p></div><button type="button" class="ui7-staff-close" data-act="staff-detail-close">×</button></div><button class="staff-btn primary ui7-staff-add" type="button" data-act="new-user">+ Tambah pegawai</button><div class="owner-list">'+list+'</div>'+userEditView()+'</section></div>':'';
  return '<div class="staff-card ui7-staff-overview"><div class="owner-head"><div><div class="staff-eyebrow">PEGAWAI · DATA PER '+esc(snapshotDate())+'</div><h1>Pegawai</h1><p>Ringkasan Staff PIN Hasnaria. Akun web email/password dikelola terpisah di Pengaturan Akun.</p></div></div><div class="ui7-staff-kpis"><div><span>Total Pegawai</span><strong>'+state.ownerRows.length+'</strong><small>master staff</small></div><div><span>Login Aktif</span><strong>'+active+'</strong><small>staff_active</small></div><div><span>PIN Siap</span><strong>'+pin+'</strong><small>PIN 6 digit tersedia</small></div><div><span>Sudah Ditugaskan</span><strong>'+assigned+'</strong><small>punya modul kerja</small></div></div><button class="staff-btn primary ui7-staff-detail-btn" type="button" data-act="staff-detail-open">Lihat Detail Pegawai</button></div>'+modal;
}
function approvalsView(){return '<div class="staff-card"><div class="staff-eyebrow">Koreksi Manual</div><h1>Persetujuan Absensi</h1><p class="staff-note">Hanya koreksi manual yang masuk ke sini. Clock In/Out normal dalam radius 50 m tidak perlu persetujuan.</p><div class="owner-approval-list">'+(state.approvals.length?state.approvals.map(function(x){return '<article class="owner-approval-card"><div><b>'+esc(x.employee_name)+'</b><small>'+esc(x.attendance_date)+' · '+(x.correction_type==='check_out'?'Clock Out':'Clock In')+' → '+esc(String(x.requested_time||'').slice(0,5))+'</small><p>'+esc(x.reason)+'</p></div><div class="staff-inline"><button class="staff-btn ghost" data-reject="'+esc(x.correction_id)+'">Tolak</button><button class="staff-btn primary" data-approve="'+esc(x.correction_id)+'">Setujui</button></div></article>';}).join(''):'<div class="staff-empty"><h2>Tidak ada koreksi pending</h2></div>')+'</div>'+note()+'</div>';}
function locationView(){var x=state.loc||{};return '<div class="staff-card"><div class="staff-eyebrow">Geofence Absensi</div><h1>Titik Warung Hasnaria</h1><p class="staff-note">Radius dikunci 50 meter. Set titik sekali saat Owner berada tepat di Warung.</p><div class="owner-location-box"><b>'+esc(x.outlet_name||'Hasnaria Main')+'</b><span>'+esc(ADDRESS)+'</span><small>Koordinat: '+coords(x.attendance_lat)+' / '+coords(x.attendance_lng)+'</small><a href="'+MAP_URL+'" target="_blank" rel="noopener">Buka Google Maps</a></div><button class="staff-btn primary" data-act="set-location">Gunakan Lokasi HP Ini sebagai Titik Warung</button>'+note()+'</div>';}
function ownerView(){var body=state.ownerTab==='approvals'?approvalsView():state.ownerTab==='location'?locationView():usersView();return '<div class="staff-shell">'+top('Keluar Owner','owner-out','Owner Mobile')+'<section class="staff-content">'+ownerNav()+body+'</section></div>';}
function render(){var r=root();if(!r)return;if(state.view==='owner-login')r.innerHTML=ownerLoginView();else if(state.view==='owner')r.innerHTML=ownerView();else if(state.view==='staff'){if(state.module==='home')r.innerHTML=homeView();else if(state.module==='absensi')r.innerHTML=attendanceView();else if(state.module==='kasir')r.innerHTML=kasirView();else r.innerHTML='<div class="staff-shell">'+top('Kembali','mod-back')+'<section class="staff-content"><div class="staff-card"><h1>Gudang</h1><p>Stok, penerimaan, dan opname.</p></div></section>'+nav()+'</div>';}else r.innerHTML=loginView();}
async function loadDirectory(){state.dir=await rpc('staff_login_directory');}
async function resumeStaff(){var t=storedToken();if(!t)return false;var a=await rpc('staff_session_info',{p_token:t});if(!a.length){saveToken('');return false;}var x=a[0];state.token=t;state.staff={employeeId:x.employee_id,fullName:x.full_name,modules:x.modules||[]};state.view='staff';state.module='home';return true;}
async function loadToday(){var a=await rpc('staff_attendance_today',{p_token:state.token});state.today=a[0]||null;}
async function loadHist(){var a=new Date(state.month.getFullYear(),state.month.getMonth(),1),b=new Date(state.month.getFullYear(),state.month.getMonth()+1,0);state.hist=await rpc('staff_attendance_history',{p_token:state.token,p_from:iso(a),p_to:iso(b)});}
async function loadCorr(){state.corr=await rpc('staff_attendance_corrections',{p_token:state.token});}
async function refreshAttendance(){await Promise.all([loadToday(),loadHist(),loadCorr()]);}
async function ownerLoad(){state.ownerRows=await rpc('staff_owner_list');state.approvals=await rpc('staff_owner_attendance_approvals');var l=await rpc('staff_owner_attendance_location');state.loc=l[0]||null;}
async function staffLogin(){var id=el('emp')&&el('emp').value,p=el('pin')&&el('pin').value;if(!id||!/^[0-9]{6}$/.test(p||'')){state.msg='Pilih nama dan masukkan PIN 6 digit.';render();return;}try{var a=await rpc('staff_pin_login',{p_employee_id:id,p_pin:p});if(!a.length)throw new Error('Login gagal.');var x=a[0];state.token=x.session_token;saveToken(state.token);state.staff={employeeId:x.employee_id,fullName:x.full_name,modules:x.modules||[]};state.view='staff';state.module='home';state.sub='';state.msg='';render();}catch(e){state.msg=errText(e);render();}}
async function staffLogout(){try{if(state.token)await rpc('staff_logout',{p_token:state.token});}catch(_){}saveToken('');state.view='login';state.staff=null;state.token='';state.module='home';state.sub='';state.msg='';try{await loadDirectory();}catch(e){state.msg=errText(e);}render();}
async function openAbs(sub){state.module='absensi';state.sub=sub||'';state.msg='';try{await refreshAttendance();}catch(e){state.msg=errText(e);}render();if(sub==='clock')gps();}
async function doClock(kind){if(!state.geo||!state.geo.inRange)return;try{var fn=kind==='in'?'staff_attendance_check_in':'staff_attendance_check_out';await rpc(fn,{p_token:state.token,p_lat:state.geo.lat,p_lng:state.geo.lng,p_accuracy_m:state.geo.accuracy,p_notes:null});state.msg=(kind==='in'?'Clock In':'Clock Out')+' berhasil dicatat tanpa approval Owner.';await loadToday();gps();}catch(e){state.msg=errText(e);render();}}
async function submitCorrection(){var type=el('ctype').value,d=el('cdate').value,t=el('ctime').value,r=el('creason').value.trim();if(!d||!t||r.length<3){state.msg='Tanggal, waktu, dan alasan wajib diisi.';render();return;}try{await rpc('staff_attendance_correction_submit',{p_token:state.token,p_correction_type:type,p_attendance_date:d,p_requested_time:t,p_reason:r,p_photo_url:null});state.msg='Koreksi dikirim dan menunggu persetujuan Owner.';await loadCorr();state.sub='mine';render();}catch(e){state.msg=errText(e);render();}}
async function ownerOpen(){try{var x=await client().auth.getSession();if(x.data&&x.data.session){state.owner=x.data.session.user;await ownerLoad();state.view='owner';state.msg='';render();return;}}catch(_){}state.view='owner-login';state.msg='';render();}
async function ownerSign(){try{var r=await client().auth.signInWithPassword({email:el('oemail').value,password:el('opass').value});if(r.error)throw r.error;state.owner=r.data.user;await ownerLoad();state.view='owner';state.msg='';render();}catch(e){state.msg=errText(e);render();}}
async function saveUser(){var mods=[];if(el('ma').checked)mods.push('absensi');if(el('mk').checked)mods.push('kasir');if(el('mg').checked)mods.push('gudang');var name=el('ename').value.trim(),pin=el('epin').value.trim(),active=el('eactive').checked;if(!name||(pin&&!/^\d{6}$/.test(pin))||(active&&!mods.length)||(active&&!state.edit.pin_set&&!pin)){state.msg='Periksa nama, PIN 6 digit, penugasan, dan status aktif.';render();return;}try{await rpc('staff_owner_save',{p_employee_id:state.edit.employee_id||null,p_full_name:name,p_pin:pin||null,p_modules:mods,p_active:active});state.edit=null;state.msg='';await ownerLoad();await loadDirectory();render();}catch(e){state.msg=errText(e);render();}}
async function decide(id,action){var reason=null;if(action==='reject'){reason=prompt('Alasan penolakan koreksi:','');if(reason===null)return;}try{await rpc('staff_owner_attendance_decide',{p_correction_id:id,p_action:action,p_reason:reason});state.msg=action==='approve'?'Koreksi disetujui.':'Koreksi ditolak.';await ownerLoad();render();}catch(e){state.msg=errText(e);render();}}
function setLocation(){if(!navigator.geolocation){state.msg='GPS tidak tersedia.';render();return;}state.msg='Mengambil lokasi HP...';render();navigator.geolocation.getCurrentPosition(async function(p){try{var a=await rpc('staff_owner_set_attendance_location',{p_lat:p.coords.latitude,p_lng:p.coords.longitude});state.loc=a[0]||null;state.msg='Titik Warung tersimpan. Radius aktif 50 m.';render();}catch(e){state.msg=errText(e);render();}},function(e){state.msg=e.message||'Izin lokasi ditolak';render();},{enableHighAccuracy:true,timeout:12000,maximumAge:0});}
document.addEventListener('click',function(e){var q=e.target.closest('[data-mod]');if(q&&!q.disabled&&state.staff){var m=q.getAttribute('data-mod');state.module=m;state.sub='';state.msg='';if(m==='absensi')openAbs('');else render();return;}q=e.target.closest('[data-sub]');if(q){state.sub=q.getAttribute('data-sub');state.msg='';if(state.module==='absensi')openAbs(state.sub);else render();return;}q=e.target.closest('[data-day]');if(q){state.selected=q.getAttribute('data-day');render();return;}q=e.target.closest('[data-month]');if(q){state.month=new Date(state.month.getFullYear(),state.month.getMonth()+Number(q.getAttribute('data-month')),1);state.selected=iso(state.month);loadHist().then(render);return;}q=e.target.closest('[data-clock]');if(q){doClock(q.getAttribute('data-clock'));return;}q=e.target.closest('[data-otab]');if(q){state.ownerTab=q.getAttribute('data-otab');state.msg='';state.edit=null;state.employeeDetailOpen=false;render();return;}q=e.target.closest('[data-edit]');if(q){var id=q.getAttribute('data-edit'),x=state.ownerRows.find(function(r){return r.employee_id===id;});state.edit={employee_id:x.employee_id,full_name:x.full_name,modules:(x.modules||[]).slice(),staff_active:!!x.staff_active,pin_set:!!x.pin_set};render();return;}q=e.target.closest('[data-approve]');if(q){decide(q.getAttribute('data-approve'),'approve');return;}q=e.target.closest('[data-reject]');if(q){decide(q.getAttribute('data-reject'),'reject');return;}q=e.target.closest('[data-act]');if(!q)return;var a=q.getAttribute('data-act');if(a==='staff-login')staffLogin();else if(a==='staff-out')staffLogout();else if(a==='owner-open')ownerOpen();else if(a==='owner-login')ownerSign();else if(a==='owner-out')client().auth.signOut().then(function(){state.view='login';state.owner=null;render();});else if(a==='login-back'){state.view='login';render();}else if(a==='att-back'){state.sub='';render();}else if(a==='mod-back'){state.module='home';state.sub='';render();}else if(a==='kasir-back'){state.sub='';render();}else if(a==='gps')gps();else if(a==='submit-corr')submitCorrection();else if(a==='staff-detail-open'){state.employeeDetailOpen=true;state.edit=null;render();}else if(a==='staff-detail-close'){state.employeeDetailOpen=false;state.edit=null;render();}else if(a==='new-user'){state.employeeDetailOpen=true;state.edit={employee_id:null,full_name:'',modules:['absensi'],staff_active:false,pin_set:false};render();}else if(a==='cancel-edit'){state.edit=null;render();}else if(a==='save-user')saveUser();else if(a==='set-location')setLocation();});
async function start(){render();try{client();await loadDirectory();await resumeStaff();}catch(e){state.msg=errText(e);}render();setInterval(function(){if(state.view==='staff'&&state.module==='absensi'&&state.sub==='clock')render();},30000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
