-- ERP foundation: shared import jobs, provenance and validation errors.
-- Existing module-specific import tables remain intact during migration.

begin;

create or replace function private.can_import_module(p_module text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select case lower(btrim(coalesce(p_module, '')))
    when 'sales' then private.has_capability('sales.write')
    when 'purchasing' then private.has_capability('stock.write')
    when 'inventory' then private.has_capability('stock.write')
    when 'bank' then private.has_role(array['owner','head_store'])
    when 'finance' then private.has_role(array['owner','head_store'])
    when 'hr' then private.has_capability('hr.manage')
    when 'marketing' then private.has_capability('marketing.manage')
    else private.has_role(array['owner'])
  end;
$$;

revoke execute on function private.can_import_module(text) from public, anon;
grant execute on function private.can_import_module(text) to authenticated;

create table if not exists public.import_jobs (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  outlet_id uuid references public.outlets(id) on delete restrict,
  module text not null,
  source_file text not null,
  file_hash text,
  status text not null default 'staged',
  period_from date,
  period_to date,
  rows_total integer not null default 0,
  rows_valid integer not null default 0,
  rows_failed integer not null default 0,
  rows_posted integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  error_summary jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint import_jobs_module_nonempty check (btrim(module) <> ''),
  constraint import_jobs_source_file_nonempty check (btrim(source_file) <> ''),
  constraint import_jobs_status_check check (status in ('staged','validating','ready','posting','completed','failed','rolled_back')),
  constraint import_jobs_rows_nonnegative check (
    rows_total >= 0 and rows_valid >= 0 and rows_failed >= 0 and rows_posted >= 0
  ),
  constraint import_jobs_rows_consistent check (
    rows_valid + rows_failed <= rows_total
    and rows_posted <= rows_valid
  ),
  constraint import_jobs_period_order check (
    period_from is null or period_to is null or period_from <= period_to
  )
);

create index if not exists import_jobs_brand_module_created_idx
  on public.import_jobs (brand_id, module, created_at desc);

create index if not exists import_jobs_outlet_created_idx
  on public.import_jobs (outlet_id, created_at desc)
  where outlet_id is not null;

create unique index if not exists import_jobs_brand_module_hash_uidx
  on public.import_jobs (brand_id, lower(btrim(module)), lower(btrim(file_hash)))
  where file_hash is not null and btrim(file_hash) <> '';

alter table public.import_jobs enable row level security;

drop policy if exists import_jobs_read_same_brand on public.import_jobs;
create policy import_jobs_read_same_brand
on public.import_jobs
for select to authenticated
using ((select private.same_brand(import_jobs.brand_id)));

drop policy if exists import_jobs_insert_authorized on public.import_jobs;
create policy import_jobs_insert_authorized
on public.import_jobs
for insert to authenticated
with check (
  (select private.same_brand(import_jobs.brand_id))
  and (select private.can_import_module(import_jobs.module))
  and (
    import_jobs.outlet_id is null
    or exists (
      select 1 from public.outlets o
      where o.id = import_jobs.outlet_id
        and o.brand_id = import_jobs.brand_id
    )
  )
);

drop policy if exists import_jobs_update_authorized on public.import_jobs;
create policy import_jobs_update_authorized
on public.import_jobs
for update to authenticated
using (
  (select private.same_brand(import_jobs.brand_id))
  and (select private.can_import_module(import_jobs.module))
)
with check (
  (select private.same_brand(import_jobs.brand_id))
  and (select private.can_import_module(import_jobs.module))
  and (
    import_jobs.outlet_id is null
    or exists (
      select 1 from public.outlets o
      where o.id = import_jobs.outlet_id
        and o.brand_id = import_jobs.brand_id
    )
  )
);

grant select, insert, update on public.import_jobs to authenticated;

create table if not exists public.import_job_errors (
  id bigint generated by default as identity primary key,
  import_job_id uuid not null references public.import_jobs(id) on delete cascade,
  row_no integer,
  error_code text not null,
  field_name text,
  message text not null,
  raw_value text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint import_job_errors_code_nonempty check (btrim(error_code) <> ''),
  constraint import_job_errors_message_nonempty check (btrim(message) <> ''),
  constraint import_job_errors_row_nonnegative check (row_no is null or row_no >= 0)
);

create index if not exists import_job_errors_job_row_idx
  on public.import_job_errors (import_job_id, row_no);

alter table public.import_job_errors enable row level security;

drop policy if exists import_job_errors_read_same_brand on public.import_job_errors;
create policy import_job_errors_read_same_brand
on public.import_job_errors
for select to authenticated
using (
  exists (
    select 1
    from public.import_jobs j
    where j.id = import_job_errors.import_job_id
      and (select private.same_brand(j.brand_id))
  )
);

drop policy if exists import_job_errors_insert_authorized on public.import_job_errors;
create policy import_job_errors_insert_authorized
on public.import_job_errors
for insert to authenticated
with check (
  exists (
    select 1
    from public.import_jobs j
    where j.id = import_job_errors.import_job_id
      and (select private.same_brand(j.brand_id))
      and (select private.can_import_module(j.module))
  )
);

grant select, insert on public.import_job_errors to authenticated;

comment on table public.import_jobs is
  'Shared ERP import batch/provenance header. Existing sales_import_batches remains supported until migrated.';
comment on table public.import_job_errors is
  'Row/field validation errors attached to a shared ERP import job.';

commit;
