create table if not exists public.user_profiles (id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
alter table public.user_profiles enable row level security;
create policy "users read own profile" on public.user_profiles for select to authenticated using (id = auth.uid());
create policy "users insert own profile" on public.user_profiles for insert to authenticated with check (id = auth.uid());
create policy "users update own profile" on public.user_profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "authenticated read brands" on public.brands for select to authenticated using (true);
create policy "authenticated manage brands" on public.brands for all to authenticated using (true) with check (true);
create policy "authenticated manage products" on public.products for all to authenticated using (true) with check (true);
create policy "authenticated manage sales" on public.sales for all to authenticated using (true) with check (true);
create policy "authenticated manage sale items" on public.sale_items for all to authenticated using (true) with check (true);
create policy "authenticated manage social contents" on public.social_contents for all to authenticated using (true) with check (true);
create policy "authenticated manage expenses" on public.expenses for all to authenticated using (true) with check (true);
create policy "authenticated manage daily metrics" on public.daily_metrics for all to authenticated using (true) with check (true);
