alter function public.get_ui_bootstrap_v6() security invoker;
revoke execute on function private.get_ui_bootstrap_v6() from public;
grant execute on function private.get_ui_bootstrap_v6() to authenticated, service_role;
revoke execute on function public.get_ui_bootstrap_v6() from public;
grant execute on function public.get_ui_bootstrap_v6() to authenticated, service_role;

alter function public.get_purchase_dual_posting_period_v1(uuid,date) set schema private;
alter function public.get_ui_action_queue_active_v1(uuid,integer) set schema private;
alter function public.get_ui_action_summary_v1(uuid) set schema private;
alter function public.get_ui_manual_input_requirements_v1(uuid) set schema private;
alter function public.get_ui_monthly_trend_v1(uuid,integer) set schema private;
alter function public.owner_daily_validation_decide_v1(uuid,text,text) set schema private;
alter function public.owner_daily_validation_queue_v1(date) set schema private;
alter function public.owner_employee_update_v1(uuid,text,numeric,numeric,text,text) set schema private;
alter function public.owner_executive_export_v1(text,date) set schema private;
alter function public.owner_executive_tab_v1(text,date) set schema private;
alter function public.owner_payroll_approve_v1(uuid) set schema private;
alter function public.owner_payroll_detail_v1(date) set schema private;
alter function public.owner_payroll_generate_v1(date) set schema private;
alter function public.owner_payroll_post_v1(uuid,text) set schema private;
alter function public.owner_payroll_set_line_v1(uuid,numeric,numeric,numeric,numeric,numeric,text) set schema private;
alter function public.owner_payroll_submit_v1(uuid) set schema private;
alter function public.staff_owner_set_supervisor_v1(uuid,boolean,text) set schema private;
alter function public.staff_owner_supervisor_state_v1() set schema private;
alter function public.staff_owner_validation_summary_v1(date) set schema private;
alter function public.sync_purchase_finance_all_open_v1() set schema private;

revoke execute on function private.get_purchase_dual_posting_period_v1(uuid,date) from public;
revoke execute on function private.get_ui_action_queue_active_v1(uuid,integer) from public;
revoke execute on function private.get_ui_action_summary_v1(uuid) from public;
revoke execute on function private.get_ui_manual_input_requirements_v1(uuid) from public;
revoke execute on function private.get_ui_monthly_trend_v1(uuid,integer) from public;
revoke execute on function private.owner_daily_validation_decide_v1(uuid,text,text) from public;
revoke execute on function private.owner_daily_validation_queue_v1(date) from public;
revoke execute on function private.owner_employee_update_v1(uuid,text,numeric,numeric,text,text) from public;
revoke execute on function private.owner_executive_export_v1(text,date) from public;
revoke execute on function private.owner_executive_tab_v1(text,date) from public;
revoke execute on function private.owner_payroll_approve_v1(uuid) from public;
revoke execute on function private.owner_payroll_detail_v1(date) from public;
revoke execute on function private.owner_payroll_generate_v1(date) from public;
revoke execute on function private.owner_payroll_post_v1(uuid,text) from public;
revoke execute on function private.owner_payroll_set_line_v1(uuid,numeric,numeric,numeric,numeric,numeric,text) from public;
revoke execute on function private.owner_payroll_submit_v1(uuid) from public;
revoke execute on function private.staff_owner_set_supervisor_v1(uuid,boolean,text) from public;
revoke execute on function private.staff_owner_supervisor_state_v1() from public;
revoke execute on function private.staff_owner_validation_summary_v1(date) from public;
revoke execute on function private.sync_purchase_finance_all_open_v1() from public;

grant execute on function private.get_purchase_dual_posting_period_v1(uuid,date) to authenticated, service_role;
grant execute on function private.get_ui_action_queue_active_v1(uuid,integer) to authenticated, service_role;
grant execute on function private.get_ui_action_summary_v1(uuid) to authenticated, service_role;
grant execute on function private.get_ui_manual_input_requirements_v1(uuid) to authenticated, service_role;
grant execute on function private.get_ui_monthly_trend_v1(uuid,integer) to authenticated, service_role;
grant execute on function private.owner_daily_validation_decide_v1(uuid,text,text) to authenticated, service_role;
grant execute on function private.owner_daily_validation_queue_v1(date) to authenticated, service_role;
grant execute on function private.owner_employee_update_v1(uuid,text,numeric,numeric,text,text) to authenticated, service_role;
grant execute on function private.owner_executive_export_v1(text,date) to authenticated, service_role;
grant execute on function private.owner_executive_tab_v1(text,date) to authenticated, service_role;
grant execute on function private.owner_payroll_approve_v1(uuid) to authenticated, service_role;
grant execute on function private.owner_payroll_detail_v1(date) to authenticated, service_role;
grant execute on function private.owner_payroll_generate_v1(date) to authenticated, service_role;
grant execute on function private.owner_payroll_post_v1(uuid,text) to authenticated, service_role;
grant execute on function private.owner_payroll_set_line_v1(uuid,numeric,numeric,numeric,numeric,numeric,text) to authenticated, service_role;
grant execute on function private.owner_payroll_submit_v1(uuid) to authenticated, service_role;
grant execute on function private.staff_owner_set_supervisor_v1(uuid,boolean,text) to authenticated, service_role;
grant execute on function private.staff_owner_supervisor_state_v1() to authenticated, service_role;
grant execute on function private.staff_owner_validation_summary_v1(date) to authenticated, service_role;
grant execute on function private.sync_purchase_finance_all_open_v1() to authenticated, service_role;

create function public.get_purchase_dual_posting_period_v1(p_brand uuid,p_period date) returns jsonb language sql security invoker set search_path='' as $$ select private.get_purchase_dual_posting_period_v1($1,$2); $$;
create function public.get_ui_action_queue_active_v1(p_brand uuid,p_limit integer default 500) returns jsonb language sql security invoker set search_path='' as $$ select private.get_ui_action_queue_active_v1($1,$2); $$;
create function public.get_ui_action_summary_v1(p_brand uuid) returns jsonb language sql security invoker set search_path='' as $$ select private.get_ui_action_summary_v1($1); $$;
create function public.get_ui_manual_input_requirements_v1(p_brand uuid) returns jsonb language sql security invoker set search_path='' as $$ select private.get_ui_manual_input_requirements_v1($1); $$;
create function public.get_ui_monthly_trend_v1(p_brand uuid,p_limit integer default 12) returns jsonb language sql security invoker set search_path='' as $$ select private.get_ui_monthly_trend_v1($1,$2); $$;
create function public.owner_daily_validation_decide_v1(p_batch_id uuid,p_action text,p_reason text default null) returns jsonb language sql security invoker set search_path='' as $$ select private.owner_daily_validation_decide_v1($1,$2,$3); $$;
create function public.owner_daily_validation_queue_v1(p_date date default null) returns jsonb language sql stable security invoker set search_path='' as $$ select private.owner_daily_validation_queue_v1($1); $$;
create function public.owner_employee_update_v1(p_employee_id uuid,p_job_title text default null,p_monthly_salary numeric default null,p_hourly_rate numeric default null,p_status text default null,p_notes text default null) returns jsonb language sql security invoker set search_path='' as $$ select private.owner_employee_update_v1($1,$2,$3,$4,$5,$6); $$;
create function public.owner_executive_export_v1(p_domain text,p_period date) returns jsonb language sql stable security invoker set search_path='' as $$ select private.owner_executive_export_v1($1,$2); $$;
create function public.owner_executive_tab_v1(p_tab text,p_period date) returns jsonb language sql stable security invoker set search_path='' as $$ select private.owner_executive_tab_v1($1,$2); $$;
create function public.owner_payroll_approve_v1(p_period_id uuid) returns jsonb language sql security invoker set search_path='' as $$ select private.owner_payroll_approve_v1($1); $$;
create function public.owner_payroll_detail_v1(p_period date) returns jsonb language sql stable security invoker set search_path='' as $$ select private.owner_payroll_detail_v1($1); $$;
create function public.owner_payroll_generate_v1(p_period date) returns jsonb language sql security invoker set search_path='' as $$ select private.owner_payroll_generate_v1($1); $$;
create function public.owner_payroll_post_v1(p_period_id uuid,p_payment_account_code text default '2190'::text) returns jsonb language sql security invoker set search_path='' as $$ select private.owner_payroll_post_v1($1,$2); $$;
create function public.owner_payroll_set_line_v1(p_line_id uuid,p_base_salary numeric default null,p_incentive numeric default null,p_overtime_pay numeric default null,p_adjustment numeric default null,p_deduction numeric default null,p_notes text default null) returns jsonb language sql security invoker set search_path='' as $$ select private.owner_payroll_set_line_v1($1,$2,$3,$4,$5,$6,$7); $$;
create function public.owner_payroll_submit_v1(p_period_id uuid) returns jsonb language sql security invoker set search_path='' as $$ select private.owner_payroll_submit_v1($1); $$;
create function public.staff_owner_set_supervisor_v1(p_employee_id uuid,p_active boolean,p_note text default null) returns jsonb language sql security invoker set search_path='' as $$ select private.staff_owner_set_supervisor_v1($1,$2,$3); $$;
create function public.staff_owner_supervisor_state_v1() returns jsonb language sql stable security invoker set search_path='' as $$ select private.staff_owner_supervisor_state_v1(); $$;
create function public.staff_owner_validation_summary_v1(p_date date default null) returns jsonb language sql stable security invoker set search_path='' as $$ select private.staff_owner_validation_summary_v1($1); $$;
create function public.sync_purchase_finance_all_open_v1() returns jsonb language sql security invoker set search_path='' as $$ select private.sync_purchase_finance_all_open_v1(); $$;

revoke execute on function public.get_purchase_dual_posting_period_v1(uuid,date) from public;
revoke execute on function public.get_ui_action_queue_active_v1(uuid,integer) from public;
revoke execute on function public.get_ui_action_summary_v1(uuid) from public;
revoke execute on function public.get_ui_manual_input_requirements_v1(uuid) from public;
revoke execute on function public.get_ui_monthly_trend_v1(uuid,integer) from public;
revoke execute on function public.owner_daily_validation_decide_v1(uuid,text,text) from public;
revoke execute on function public.owner_daily_validation_queue_v1(date) from public;
revoke execute on function public.owner_employee_update_v1(uuid,text,numeric,numeric,text,text) from public;
revoke execute on function public.owner_executive_export_v1(text,date) from public;
revoke execute on function public.owner_executive_tab_v1(text,date) from public;
revoke execute on function public.owner_payroll_approve_v1(uuid) from public;
revoke execute on function public.owner_payroll_detail_v1(date) from public;
revoke execute on function public.owner_payroll_generate_v1(date) from public;
revoke execute on function public.owner_payroll_post_v1(uuid,text) from public;
revoke execute on function public.owner_payroll_set_line_v1(uuid,numeric,numeric,numeric,numeric,numeric,text) from public;
revoke execute on function public.owner_payroll_submit_v1(uuid) from public;
revoke execute on function public.staff_owner_set_supervisor_v1(uuid,boolean,text) from public;
revoke execute on function public.staff_owner_supervisor_state_v1() from public;
revoke execute on function public.staff_owner_validation_summary_v1(date) from public;
revoke execute on function public.sync_purchase_finance_all_open_v1() from public;

grant execute on function public.get_purchase_dual_posting_period_v1(uuid,date) to authenticated, service_role;
grant execute on function public.get_ui_action_queue_active_v1(uuid,integer) to authenticated, service_role;
grant execute on function public.get_ui_action_summary_v1(uuid) to authenticated, service_role;
grant execute on function public.get_ui_manual_input_requirements_v1(uuid) to authenticated, service_role;
grant execute on function public.get_ui_monthly_trend_v1(uuid,integer) to authenticated, service_role;
grant execute on function public.owner_daily_validation_decide_v1(uuid,text,text) to authenticated, service_role;
grant execute on function public.owner_daily_validation_queue_v1(date) to authenticated, service_role;
grant execute on function public.owner_employee_update_v1(uuid,text,numeric,numeric,text,text) to authenticated, service_role;
grant execute on function public.owner_executive_export_v1(text,date) to authenticated, service_role;
grant execute on function public.owner_executive_tab_v1(text,date) to authenticated, service_role;
grant execute on function public.owner_payroll_approve_v1(uuid) to authenticated, service_role;
grant execute on function public.owner_payroll_detail_v1(date) to authenticated, service_role;
grant execute on function public.owner_payroll_generate_v1(date) to authenticated, service_role;
grant execute on function public.owner_payroll_post_v1(uuid,text) to authenticated, service_role;
grant execute on function public.owner_payroll_set_line_v1(uuid,numeric,numeric,numeric,numeric,numeric,text) to authenticated, service_role;
grant execute on function public.owner_payroll_submit_v1(uuid) to authenticated, service_role;
grant execute on function public.staff_owner_set_supervisor_v1(uuid,boolean,text) to authenticated, service_role;
grant execute on function public.staff_owner_supervisor_state_v1() to authenticated, service_role;
grant execute on function public.staff_owner_validation_summary_v1(date) to authenticated, service_role;
grant execute on function public.sync_purchase_finance_all_open_v1() to authenticated, service_role;
