-- ERP control-plane foundation: approval rules/requests/history, audit log and exception events.
-- Additive and independent from existing expense approval until module-by-module migration.

begin;

create table if not exists public.approval_rules (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  transaction_type text not null,
  category text,
  requester_role text,
  min_amount numeric not null default 0,
  max_amount numeric,
  approver_role text not null,
  priority integer not null default 100,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint approval_rules_transaction_nonempty check (btrim(transaction_type) <> ''),
  constraint approval_rules_approver_nonempty check (btrim(approver_role) <> ''),
  constraint approval_rules_amounts_valid check (
    min_amount >= 0 and (max_amount is null or max_amount >= min_amount)
  )
);

create index if not exists approval_rules_match_idx
  on public.approval_rules (brand_id, transaction_type, category, active, priority, min_amount);

alter table public.approval_rules enable row level security;

drop policy if exists approval_rules_read_same_brand on public.approval_rules;
create policy approval_rules_read_same_brand
on public.approval_rules
for select to authenticated
using ((select private.same_brand(approval_rules.brand_id)));

drop policy if exists approval_rules_owner_write on public.approval_rules;
create policy approval_rules_owner_write
on public.approval_rules
for all to authenticated
using (
  (select private.same_brand(approval_rules.brand_id))
  and (
    (select private.has_capability('settings.manage'))
    or (select private.is_super_admin())
  )
)
with check (
  (select private.same_brand(approval_rules.brand_id))
  and (
    (select private.has_capability('settings.manage'))
    or (select private.is_super_admin())
  )
);

grant select, insert, update, delete on public.approval_rules to authenticated;

create table if not exists public.approval_requests (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  outlet_id uuid references public.outlets(id) on delete restrict,
  rule_id uuid references public.approval_rules(id) on delete set null,
  entity_type text not null,
  entity_id uuid not null,
  amount numeric,
  currency text not null default 'IDR',
  approver_role text not null,
  status text not null default 'pending',
  requested_by uuid not null references auth.users(id) on delete restrict default auth.uid(),
  requested_at timestamptz not null default now(),
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  decision_reason text,
  metadata jsonb not null default '{}'::jsonb,
  constraint approval_requests_entity_nonempty check (btrim(entity_type) <> ''),
  constraint approval_requests_approver_nonempty check (btrim(approver_role) <> ''),
  constraint approval_requests_amount_nonnegative check (amount is null or amount >= 0),
  constraint approval_requests_status_check check (status in ('pending','approved','rejected','cancelled')),
  constraint approval_requests_currency_nonempty check (btrim(currency) <> '')
);

create index if not exists approval_requests_brand_status_idx
  on public.approval_requests (brand_id, status, requested_at desc);

create index if not exists approval_requests_entity_idx
  on public.approval_requests (entity_type, entity_id);

create unique index if not exists approval_requests_one_pending_entity_uidx
  on public.approval_requests (brand_id, entity_type, entity_id)
  where status = 'pending';

alter table public.approval_requests enable row level security;

drop policy if exists approval_requests_read_same_brand on public.approval_requests;
create policy approval_requests_read_same_brand
on public.approval_requests
for select to authenticated
using ((select private.same_brand(approval_requests.brand_id)));

drop policy if exists approval_requests_insert_same_brand on public.approval_requests;
create policy approval_requests_insert_same_brand
on public.approval_requests
for insert to authenticated
with check (
  (select private.same_brand(approval_requests.brand_id))
  and approval_requests.requested_by = (select auth.uid())
  and (
    approval_requests.outlet_id is null
    or exists (
      select 1 from public.outlets o
      where o.id = approval_requests.outlet_id
        and o.brand_id = approval_requests.brand_id
    )
  )
);

grant select, insert on public.approval_requests to authenticated;

create table if not exists public.approval_history (
  id bigint generated by default as identity primary key,
  approval_request_id uuid not null references public.approval_requests(id) on delete cascade,
  action text not null,
  actor_id uuid references auth.users(id) on delete set null default auth.uid(),
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint approval_history_action_check check (action in ('requested','approved','rejected','cancelled','reopened'))
);

create index if not exists approval_history_request_created_idx
  on public.approval_history (approval_request_id, created_at);

alter table public.approval_history enable row level security;

drop policy if exists approval_history_read_same_brand on public.approval_history;
create policy approval_history_read_same_brand
on public.approval_history
for select to authenticated
using (
  exists (
    select 1 from public.approval_requests r
    where r.id = approval_history.approval_request_id
      and (select private.same_brand(r.brand_id))
  )
);

grant select on public.approval_history to authenticated;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  outlet_id uuid references public.outlets(id) on delete set null,
  entity_type text not null,
  entity_id uuid,
  action text not null,
  actor_id uuid references auth.users(id) on delete set null,
  before_data jsonb,
  after_data jsonb,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint audit_logs_entity_nonempty check (btrim(entity_type) <> ''),
  constraint audit_logs_action_nonempty check (btrim(action) <> '')
);

create index if not exists audit_logs_brand_created_idx
  on public.audit_logs (brand_id, created_at desc);

create index if not exists audit_logs_entity_idx
  on public.audit_logs (entity_type, entity_id, created_at desc);

alter table public.audit_logs enable row level security;

drop policy if exists audit_logs_owner_read on public.audit_logs;
create policy audit_logs_owner_read
on public.audit_logs
for select to authenticated
using (
  (select private.same_brand(audit_logs.brand_id))
  and (
    (select private.has_capability('audit.read'))
    or (select private.is_super_admin())
  )
);

grant select on public.audit_logs to authenticated;

create or replace function private.write_audit_log(
  p_brand_id uuid,
  p_outlet_id uuid,
  p_entity_type text,
  p_entity_id uuid,
  p_action text,
  p_actor_id uuid,
  p_before_data jsonb,
  p_after_data jsonb,
  p_reason text,
  p_metadata jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.audit_logs (
    brand_id, outlet_id, entity_type, entity_id, action, actor_id,
    before_data, after_data, reason, metadata
  ) values (
    p_brand_id, p_outlet_id, p_entity_type, p_entity_id, p_action,
    coalesce(p_actor_id, auth.uid()), p_before_data, p_after_data, p_reason,
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

revoke execute on function private.write_audit_log(uuid,uuid,text,uuid,text,uuid,jsonb,jsonb,text,jsonb)
  from public, anon, authenticated;

create or replace function public.decide_approval_request(
  p_request_id uuid,
  p_action text,
  p_reason text default null
)
returns public.approval_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request public.approval_requests%rowtype;
  v_role text;
  v_is_super boolean;
begin
  if lower(btrim(coalesce(p_action, ''))) not in ('approved','rejected') then
    raise exception 'Unsupported approval action';
  end if;

  select role, is_super_admin
    into v_role, v_is_super
  from public.user_profiles
  where id = auth.uid()
    and status = 'active';

  if v_role is null and coalesce(v_is_super, false) = false then
    raise exception 'Active profile required';
  end if;

  select *
    into v_request
  from public.approval_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'Approval request not found';
  end if;

  if not private.same_brand(v_request.brand_id) then
    raise exception 'Approval request is outside your brand';
  end if;

  if v_request.status <> 'pending' then
    raise exception 'Approval request is no longer pending';
  end if;

  if v_request.requested_by = auth.uid() then
    raise exception 'Self-approval is not allowed';
  end if;

  if not coalesce(v_is_super, false)
     and v_role <> v_request.approver_role
     and not (v_role = 'owner' and v_request.approver_role = 'head_store') then
    raise exception 'You are not an authorized approver for this request';
  end if;

  update public.approval_requests
  set
    status = lower(btrim(p_action)),
    resolved_by = auth.uid(),
    resolved_at = now(),
    decision_reason = nullif(btrim(coalesce(p_reason, '')), '')
  where id = v_request.id
  returning * into v_request;

  insert into public.approval_history (
    approval_request_id, action, actor_id, reason
  ) values (
    v_request.id, v_request.status, auth.uid(), v_request.decision_reason
  );

  perform private.write_audit_log(
    v_request.brand_id,
    v_request.outlet_id,
    'approval_request',
    v_request.id,
    v_request.status,
    auth.uid(),
    jsonb_build_object('status', 'pending'),
    jsonb_build_object('status', v_request.status, 'resolved_by', auth.uid(), 'resolved_at', v_request.resolved_at),
    v_request.decision_reason,
    jsonb_build_object('entity_type', v_request.entity_type, 'entity_id', v_request.entity_id)
  );

  return v_request;
end;
$$;

revoke execute on function public.decide_approval_request(uuid,text,text) from public, anon;
grant execute on function public.decide_approval_request(uuid,text,text) to authenticated;

create table if not exists public.exception_events (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  outlet_id uuid references public.outlets(id) on delete set null,
  event_code text not null,
  severity text not null,
  entity_type text,
  entity_id uuid,
  title text not null,
  detail text,
  detected_at timestamptz not null default now(),
  acknowledged_by uuid references auth.users(id) on delete set null,
  acknowledged_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  resolution_note text,
  metadata jsonb not null default '{}'::jsonb,
  constraint exception_events_code_nonempty check (btrim(event_code) <> ''),
  constraint exception_events_title_nonempty check (btrim(title) <> ''),
  constraint exception_events_severity_check check (severity in ('INFO','WARNING','CRITICAL'))
);

create index if not exists exception_events_brand_open_idx
  on public.exception_events (brand_id, severity, detected_at desc)
  where resolved_at is null;

alter table public.exception_events enable row level security;

drop policy if exists exception_events_read_same_brand on public.exception_events;
create policy exception_events_read_same_brand
on public.exception_events
for select to authenticated
using ((select private.same_brand(exception_events.brand_id)));

grant select on public.exception_events to authenticated;

comment on table public.approval_rules is 'Configurable ERP approval routing rules; existing expense approval remains active until migrated.';
comment on table public.approval_requests is 'Generic approval queue for ERP entities.';
comment on table public.approval_history is 'Append-only approval decision history.';
comment on table public.audit_logs is 'Append-only business audit trail. Clients have no direct insert/update/delete grant.';
comment on table public.exception_events is 'Business exceptions/alerts consumed by the executive Decision Center.';

commit;
